# yaml-language-server: $schema=../../.helm-shared/values.schema.json

ioc-instance:
  image: ghcr.io/epics-containers/ioc-pmac-runtime:2025.11.1

  volumes:
    - name: dev-shm
      emptyDir:
        medium: Memory
        sizeLimit: 1Gi

  volumeMounts:
    - name: dev-shm
      mountPath: /dev/shm
