# yaml-language-server: $schema=../../../ibek-runtime-support/runtime.schema.json
ioc_name: "{{ _global.get_env('IOC_NAME') }}"

description: additional entities from the services repo

entities:
  - type: detectorPlugins.detectorPlugins
    P: BL47P-EA-DET-01
    CAM: DET.CAM
    PORTPREFIX: DET
